/**
 * SYSTEM_ROLES — الأدوار الافتراضية المُنشأة من seed.
 * المرجع: docs/04-rbac-permissions.md (القسم 5).
 */

import { PERMISSIONS, ALL_PERMISSION_CODES } from './permissions';

export const SYSTEM_ROLE_NAMES = {
  OWNER: 'Owner',
  MANAGER: 'Manager',
  SALES_WORKER: 'SalesWorker',
  ACCOUNTANT: 'Accountant',
  PURCHASING_OFFICER: 'PurchasingOfficer',
  INVENTORY_OFFICER: 'InventoryOfficer',
} as const;

export type SystemRoleName = (typeof SYSTEM_ROLE_NAMES)[keyof typeof SYSTEM_ROLE_NAMES];

export interface SystemRoleSeed {
  name: SystemRoleName;
  labelAr: string;
  description: string;
  permissions: string[];
}

const MANAGER_EXCLUSIONS = new Set<string>([
  PERMISSIONS.SYSTEM.BACKUP_RESTORE,
  PERMISSIONS.USERS.DELETE,
  PERMISSIONS.ROLES.DELETE,
]);

export const SYSTEM_ROLES: SystemRoleSeed[] = [
  {
    name: SYSTEM_ROLE_NAMES.OWNER,
    labelAr: 'المالك',
    description: 'صلاحيات كاملة على النظام (super-admin)',
    permissions: [...ALL_PERMISSION_CODES],
  },
  {
    name: SYSTEM_ROLE_NAMES.MANAGER,
    labelAr: 'المدير',
    description: 'كل الصلاحيات ما عدا حذف المستخدمين/الأدوار وعمليات الاستعادة',
    permissions: ALL_PERMISSION_CODES.filter((p) => !MANAGER_EXCLUSIONS.has(p)),
  },
  {
    name: SYSTEM_ROLE_NAMES.SALES_WORKER,
    labelAr: 'عامل مبيعات',
    description: 'إنشاء عملاء، بيع، تسجيل ديون وسداد',
    permissions: [
      PERMISSIONS.CUSTOMERS.VIEW,
      PERMISSIONS.CUSTOMERS.CREATE,
      PERMISSIONS.CUSTOMER_TRANSACTIONS.VIEW,
      PERMISSIONS.CUSTOMER_TRANSACTIONS.CREATE_DEBT,
      PERMISSIONS.CUSTOMER_TRANSACTIONS.CREATE_PAYMENT,
      PERMISSIONS.CUSTOMER_TRANSACTIONS.PRINT_RECEIPT,
      PERMISSIONS.SALES.VIEW,
      PERMISSIONS.SALES.CREATE,
      PERMISSIONS.SALES.CREATE_QUICK,
      PERMISSIONS.SALES.CREATE_CREDIT,
      PERMISSIONS.SALES.CREATE_CASH,
      PERMISSIONS.SALES.PRINT_RECEIPT,
      PERMISSIONS.DAILY_INCOME.CREATE,
      PERMISSIONS.NOTIFICATIONS.VIEW_OWN,
      PERMISSIONS.NOTIFICATIONS.MARK_READ,
    ],
  },
  {
    name: SYSTEM_ROLE_NAMES.ACCOUNTANT,
    labelAr: 'محاسب',
    description: 'مراجعة مالية وتقارير الأرباح والمصاريف',
    permissions: [
      PERMISSIONS.CUSTOMERS.VIEW,
      PERMISSIONS.CUSTOMERS.VIEW_BALANCE,
      PERMISSIONS.CUSTOMERS.VIEW_TRANSACTIONS,
      PERMISSIONS.SUPPLIERS.VIEW,
      PERMISSIONS.SUPPLIERS.VIEW_BALANCE,
      PERMISSIONS.SUPPLIERS.VIEW_TRANSACTIONS,
      PERMISSIONS.EXPENSES.VIEW,
      PERMISSIONS.EXPENSES.CREATE,
      PERMISSIONS.EXPENSES.CREATE_NORMAL,
      PERMISSIONS.DAILY_INCOME.VIEW,
      PERMISSIONS.REPORTS.DASHBOARD_VIEW,
      PERMISSIONS.REPORTS.DAILY_SUMMARY_VIEW,
      PERMISSIONS.REPORTS.MONTHLY_SUMMARY_VIEW,
      PERMISSIONS.REPORTS.PROFIT_LOSS_VIEW,
      PERMISSIONS.REPORTS.CASH_FLOW_VIEW,
      PERMISSIONS.REPORTS.PRINT_MONTHLY_SUMMARY,
      PERMISSIONS.REPORTS.PRINT_PROFIT_LOSS,
      PERMISSIONS.REPORTS.EXPORT_MONTHLY_SUMMARY,
      PERMISSIONS.AUDIT_LOGS.VIEW,
      PERMISSIONS.NOTIFICATIONS.VIEW_OWN,
      PERMISSIONS.NOTIFICATIONS.MARK_READ,
    ],
  },
  {
    name: SYSTEM_ROLE_NAMES.PURCHASING_OFFICER,
    labelAr: 'مسؤول مشتريات',
    description: 'إدارة الموردين والمشتريات',
    permissions: [
      PERMISSIONS.SUPPLIERS.VIEW,
      PERMISSIONS.SUPPLIERS.CREATE,
      PERMISSIONS.SUPPLIERS.UPDATE,
      PERMISSIONS.SUPPLIERS.VIEW_BALANCE,
      PERMISSIONS.SUPPLIERS.VIEW_TRANSACTIONS,
      PERMISSIONS.SUPPLIER_TRANSACTIONS.VIEW,
      PERMISSIONS.SUPPLIER_TRANSACTIONS.CREATE_CREDIT_PURCHASE,
      PERMISSIONS.SUPPLIER_TRANSACTIONS.CREATE_PAYMENT,
      PERMISSIONS.PURCHASES.VIEW,
      PERMISSIONS.PURCHASES.CREATE,
      PERMISSIONS.PURCHASES.CREATE_CASH,
      PERMISSIONS.PURCHASES.CREATE_CREDIT,
      PERMISSIONS.PURCHASES.CREATE_WITH_ITEMS,
      PERMISSIONS.PURCHASES.CREATE_TOTAL_ONLY,
      PERMISSIONS.PURCHASES.PRINT_INVOICE,
      PERMISSIONS.PRODUCTS.VIEW,
      PERMISSIONS.PRODUCTS.CREATE,
      PERMISSIONS.STOCK_MOVEMENTS.CREATE_IN,
      PERMISSIONS.NOTIFICATIONS.VIEW_OWN,
      PERMISSIONS.NOTIFICATIONS.MARK_READ,
    ],
  },
  {
    name: SYSTEM_ROLE_NAMES.INVENTORY_OFFICER,
    labelAr: 'مسؤول مخزون',
    description: 'إدارة المنتجات وحركات المخزون',
    permissions: [
      PERMISSIONS.PRODUCTS.VIEW,
      PERMISSIONS.PRODUCTS.CREATE,
      PERMISSIONS.PRODUCTS.UPDATE,
      PERMISSIONS.PRODUCTS.PAUSE,
      PERMISSIONS.PRODUCTS.ACTIVATE,
      PERMISSIONS.PRODUCTS.MANAGE_PRICES,
      PERMISSIONS.INVENTORY.VIEW,
      PERMISSIONS.STOCK_MOVEMENTS.VIEW,
      PERMISSIONS.STOCK_MOVEMENTS.CREATE_IN,
      PERMISSIONS.STOCK_MOVEMENTS.CREATE_OUT,
      PERMISSIONS.STOCK_MOVEMENTS.ADJUST,
      PERMISSIONS.REPORTS.INVENTORY_VIEW,
      PERMISSIONS.REPORTS.PRINT_INVENTORY,
      PERMISSIONS.NOTIFICATIONS.VIEW_OWN,
      PERMISSIONS.NOTIFICATIONS.MARK_READ,
    ],
  },
];
